// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct TabSpec {
  var index: Int64
  var iconName: String
  var label: String
  var accessibilityLabel: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TabSpec? {
    let index = pigeonVar_list[0] as! Int64
    let iconName = pigeonVar_list[1] as! String
    let label = pigeonVar_list[2] as! String
    let accessibilityLabel = pigeonVar_list[3] as! String

    return TabSpec(
      index: index,
      iconName: iconName,
      label: label,
      accessibilityLabel: accessibilityLabel
    )
  }
  func toList() -> [Any?] {
    return [
      index,
      iconName,
      label,
      accessibilityLabel,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ChromeAction {
  var id: String
  var iconName: String
  var title: String
  var isDestructive: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ChromeAction? {
    let id = pigeonVar_list[0] as! String
    let iconName = pigeonVar_list[1] as! String
    let title = pigeonVar_list[2] as! String
    let isDestructive = pigeonVar_list[3] as! Bool

    return ChromeAction(
      id: id,
      iconName: iconName,
      title: title,
      isDestructive: isDestructive
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      iconName,
      title,
      isDestructive,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PageChromeSpec {
  var title: String
  var largeTitle: Bool
  var showBack: Bool
  var backLabel: String? = nil
  var actions: [ChromeAction?]
  var toolbarActions: [ChromeAction?]
  var languageCode: String
  var isRTL: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PageChromeSpec? {
    let title = pigeonVar_list[0] as! String
    let largeTitle = pigeonVar_list[1] as! Bool
    let showBack = pigeonVar_list[2] as! Bool
    let backLabel: String? = nilOrValue(pigeonVar_list[3])
    let actions = pigeonVar_list[4] as! [ChromeAction?]
    let toolbarActions = pigeonVar_list[5] as! [ChromeAction?]
    let languageCode = pigeonVar_list[6] as! String
    let isRTL = pigeonVar_list[7] as! Bool

    return PageChromeSpec(
      title: title,
      largeTitle: largeTitle,
      showBack: showBack,
      backLabel: backLabel,
      actions: actions,
      toolbarActions: toolbarActions,
      languageCode: languageCode,
      isRTL: isRTL
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      largeTitle,
      showBack,
      backLabel,
      actions,
      toolbarActions,
      languageCode,
      isRTL,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ChromeInsets {
  var top: Double
  var bottom: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ChromeInsets? {
    let top = pigeonVar_list[0] as! Double
    let bottom = pigeonVar_list[1] as! Double

    return ChromeInsets(
      top: top,
      bottom: bottom
    )
  }
  func toList() -> [Any?] {
    return [
      top,
      bottom,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ActionSheetItem {
  var id: String
  var title: String
  var isDestructive: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ActionSheetItem? {
    let id = pigeonVar_list[0] as! String
    let title = pigeonVar_list[1] as! String
    let isDestructive = pigeonVar_list[2] as! Bool

    return ActionSheetItem(
      id: id,
      title: title,
      isDestructive: isDestructive
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      isDestructive,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ActionSheetSpec {
  var title: String? = nil
  var message: String? = nil
  var items: [ActionSheetItem?]
  var cancelLabel: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ActionSheetSpec? {
    let title: String? = nilOrValue(pigeonVar_list[0])
    let message: String? = nilOrValue(pigeonVar_list[1])
    let items = pigeonVar_list[2] as! [ActionSheetItem?]
    let cancelLabel = pigeonVar_list[3] as! String

    return ActionSheetSpec(
      title: title,
      message: message,
      items: items,
      cancelLabel: cancelLabel
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      message,
      items,
      cancelLabel,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AlertSpec {
  var title: String
  var message: String? = nil
  var confirmLabel: String
  var cancelLabel: String
  var isDestructive: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AlertSpec? {
    let title = pigeonVar_list[0] as! String
    let message: String? = nilOrValue(pigeonVar_list[1])
    let confirmLabel = pigeonVar_list[2] as! String
    let cancelLabel = pigeonVar_list[3] as! String
    let isDestructive = pigeonVar_list[4] as! Bool

    return AlertSpec(
      title: title,
      message: message,
      confirmLabel: confirmLabel,
      cancelLabel: cancelLabel,
      isDestructive: isDestructive
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      message,
      confirmLabel,
      cancelLabel,
      isDestructive,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MenuSpec {
  var items: [ActionSheetItem?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MenuSpec? {
    let items = pigeonVar_list[0] as! [ActionSheetItem?]

    return MenuSpec(
      items: items
    )
  }
  func toList() -> [Any?] {
    return [
      items
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AnchorRect {
  var x: Double
  var y: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnchorRect? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return AnchorRect(
      x: x,
      y: y,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      width,
      height,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DatePickerSpec {
  var mode: String
  var initialTimestamp: Int64? = nil
  var minTimestamp: Int64? = nil
  var maxTimestamp: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DatePickerSpec? {
    let mode = pigeonVar_list[0] as! String
    let initialTimestamp: Int64? = nilOrValue(pigeonVar_list[1])
    let minTimestamp: Int64? = nilOrValue(pigeonVar_list[2])
    let maxTimestamp: Int64? = nilOrValue(pigeonVar_list[3])

    return DatePickerSpec(
      mode: mode,
      initialTimestamp: initialTimestamp,
      minTimestamp: minTimestamp,
      maxTimestamp: maxTimestamp
    )
  }
  func toList() -> [Any?] {
    return [
      mode,
      initialTimestamp,
      minTimestamp,
      maxTimestamp,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CapabilitiesSpec {
  var osVersion: String
  var glassAvailable: Bool
  var reduceTransparency: Bool
  var reduceMotion: Bool
  var dynamicTypeScale: Double
  var darkMode: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CapabilitiesSpec? {
    let osVersion = pigeonVar_list[0] as! String
    let glassAvailable = pigeonVar_list[1] as! Bool
    let reduceTransparency = pigeonVar_list[2] as! Bool
    let reduceMotion = pigeonVar_list[3] as! Bool
    let dynamicTypeScale = pigeonVar_list[4] as! Double
    let darkMode = pigeonVar_list[5] as! Bool

    return CapabilitiesSpec(
      osVersion: osVersion,
      glassAvailable: glassAvailable,
      reduceTransparency: reduceTransparency,
      reduceMotion: reduceMotion,
      dynamicTypeScale: dynamicTypeScale,
      darkMode: darkMode
    )
  }
  func toList() -> [Any?] {
    return [
      osVersion,
      glassAvailable,
      reduceTransparency,
      reduceMotion,
      dynamicTypeScale,
      darkMode,
    ]
  }
}

private class ChromeMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return TabSpec.fromList(self.readValue() as! [Any?])
    case 130:
      return ChromeAction.fromList(self.readValue() as! [Any?])
    case 131:
      return PageChromeSpec.fromList(self.readValue() as! [Any?])
    case 132:
      return ChromeInsets.fromList(self.readValue() as! [Any?])
    case 133:
      return ActionSheetItem.fromList(self.readValue() as! [Any?])
    case 134:
      return ActionSheetSpec.fromList(self.readValue() as! [Any?])
    case 135:
      return AlertSpec.fromList(self.readValue() as! [Any?])
    case 136:
      return MenuSpec.fromList(self.readValue() as! [Any?])
    case 137:
      return AnchorRect.fromList(self.readValue() as! [Any?])
    case 138:
      return DatePickerSpec.fromList(self.readValue() as! [Any?])
    case 139:
      return CapabilitiesSpec.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ChromeMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TabSpec {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ChromeAction {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PageChromeSpec {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? ChromeInsets {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ActionSheetItem {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ActionSheetSpec {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? AlertSpec {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? MenuSpec {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? AnchorRect {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? DatePickerSpec {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? CapabilitiesSpec {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ChromeMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ChromeMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ChromeMessagesPigeonCodecWriter(data: data)
  }
}

class ChromeMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ChromeMessagesPigeonCodec(readerWriter: ChromeMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ChromeHostApi {
  func configureTabs(tabs: [TabSpec]) throws
  func setSelectedTab(index: Int64) throws
  func setPageChrome(spec: PageChromeSpec) throws
  func setChromeVisible(navBar: Bool, tabBar: Bool) throws
  /// 'glass' | 'opaque'.
  ///
  /// Semantics, not styling: Dart says which *kind* of background the bars
  /// should ask the system for, and Swift picks between two system-provided
  /// appearance configurations. No blur radius, tint or colour crosses this
  /// wire — see PLATFORM_UI_ARCHITECTURE §10.
  ///
  /// Exists so the app's glass setting (and Reduce Transparency) reach the
  /// native bars too. Without it, turning glass off produced solid content
  /// under still-translucent chrome.
  func setChromeStyle(style: String) throws
  /// Whether page content is currently underneath the bars.
  ///
  /// The missing half of iOS's scroll edge effect. UIKit normally derives this
  /// itself from a connected `UIScrollView`, but Flutter owns the scroll view
  /// here and the bars are standalone, so nothing could observe it — which is
  /// why both bars were pinned to a single appearance and always showed their
  /// material. Dart sends the fact; Swift picks the appearance.
  func setScrollEdge(underContent: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ChromeHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ChromeMessagesPigeonCodec.shared }
  /// Sets up an instance of `ChromeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ChromeHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let configureTabsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wellness_app.ChromeHostApi.configureTabs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureTabsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tabsArg = args[0] as! [TabSpec]
        do {
          try api.configureTabs(tabs: tabsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureTabsChannel.setMessageHandler(nil)
    }
    let setSelectedTabChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wellness_app.ChromeHostApi.setSelectedTab\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSelectedTabChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let indexArg = args[0] as! Int64
        do {
          try api.setSelectedTab(index: indexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSelectedTabChannel.setMessageHandler(nil)
    }
    let setPageChromeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wellness_app.ChromeHostApi.setPageChrome\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPageChromeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let specArg = args[0] as! PageChromeSpec
        do {
          try api.setPageChrome(spec: specArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPageChromeChannel.setMessageHandler(nil)
    }
    let setChromeVisibleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wellness_app.ChromeHostApi.setChromeVisible\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setChromeVisibleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let navBarArg = args[0] as! Bool
        let tabBarArg = args[1] as! Bool
        do {
          try api.setChromeVisible(navBar: navBarArg, tabBar: tabBarArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setChromeVisibleChannel.setMessageHandler(nil)
    }
    /// 'glass' | 'opaque'.
    ///
    /// Semantics, not styling: Dart says which *kind* of background the bars
    /// should ask the system for, and Swift picks between two system-provided
    /// appearance configurations. No blur radius, tint or colour crosses this
    /// wire — see PLATFORM_UI_ARCHITECTURE §10.
    ///
    /// Exists so the app's glass setting (and Reduce Transparency) reach the
    /// native bars too. Without it, turning glass off produced solid content
    /// under still-translucent chrome.
    let setChromeStyleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wellness_app.ChromeHostApi.setChromeStyle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setChromeStyleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let styleArg = args[0] as! String
        do {
          try api.setChromeStyle(style: styleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setChromeStyleChannel.setMessageHandler(nil)
    }
    /// Whether page content is currently underneath the bars.
    ///
    /// The missing half of iOS's scroll edge effect. UIKit normally derives this
    /// itself from a connected `UIScrollView`, but Flutter owns the scroll view
    /// here and the bars are standalone, so nothing could observe it — which is
    /// why both bars were pinned to a single appearance and always showed their
    /// material. Dart sends the fact; Swift picks the appearance.
    let setScrollEdgeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wellness_app.ChromeHostApi.setScrollEdge\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setScrollEdgeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let underContentArg = args[0] as! Bool
        do {
          try api.setScrollEdge(underContent: underContentArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setScrollEdgeChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PresentationHostApi {
  func presentActionSheet(spec: ActionSheetSpec, completion: @escaping (Result<String?, Error>) -> Void)
  func presentAlert(spec: AlertSpec, completion: @escaping (Result<Bool, Error>) -> Void)
  func presentMenu(spec: MenuSpec, anchor: AnchorRect, completion: @escaping (Result<String?, Error>) -> Void)
  func presentDatePicker(spec: DatePickerSpec, completion: @escaping (Result<Int64?, Error>) -> Void)
  func presentShare(paths: [String], anchor: AnchorRect, completion: @escaping (Result<Void, Error>) -> Void)
  func haptic(kind: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PresentationHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ChromeMessagesPigeonCodec.shared }
  /// Sets up an instance of `PresentationHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PresentationHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let presentActionSheetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wellness_app.PresentationHostApi.presentActionSheet\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentActionSheetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let specArg = args[0] as! ActionSheetSpec
        api.presentActionSheet(spec: specArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      presentActionSheetChannel.setMessageHandler(nil)
    }
    let presentAlertChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wellness_app.PresentationHostApi.presentAlert\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentAlertChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let specArg = args[0] as! AlertSpec
        api.presentAlert(spec: specArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      presentAlertChannel.setMessageHandler(nil)
    }
    let presentMenuChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wellness_app.PresentationHostApi.presentMenu\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentMenuChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let specArg = args[0] as! MenuSpec
        let anchorArg = args[1] as! AnchorRect
        api.presentMenu(spec: specArg, anchor: anchorArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      presentMenuChannel.setMessageHandler(nil)
    }
    let presentDatePickerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wellness_app.PresentationHostApi.presentDatePicker\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentDatePickerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let specArg = args[0] as! DatePickerSpec
        api.presentDatePicker(spec: specArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      presentDatePickerChannel.setMessageHandler(nil)
    }
    let presentShareChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wellness_app.PresentationHostApi.presentShare\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentShareChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathsArg = args[0] as! [String]
        let anchorArg = args[1] as! AnchorRect
        api.presentShare(paths: pathsArg, anchor: anchorArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      presentShareChannel.setMessageHandler(nil)
    }
    let hapticChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wellness_app.PresentationHostApi.haptic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hapticChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let kindArg = args[0] as! String
        do {
          try api.haptic(kind: kindArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hapticChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CapabilitiesApi {
  func read() throws -> CapabilitiesSpec
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CapabilitiesApiSetup {
  static var codec: FlutterStandardMessageCodec { ChromeMessagesPigeonCodec.shared }
  /// Sets up an instance of `CapabilitiesApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CapabilitiesApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let readChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wellness_app.CapabilitiesApi.read\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readChannel.setMessageHandler { _, reply in
        do {
          let result = try api.read()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      readChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ChromeFlutterApiProtocol {
  func onTabSelected(index indexArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onChromeAction(actionId actionIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBackPressed(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onInsetsChanged(insets insetsArg: ChromeInsets, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ChromeFlutterApi: ChromeFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ChromeMessagesPigeonCodec {
    return ChromeMessagesPigeonCodec.shared
  }
  func onTabSelected(index indexArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wellness_app.ChromeFlutterApi.onTabSelected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([indexArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onChromeAction(actionId actionIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wellness_app.ChromeFlutterApi.onChromeAction\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([actionIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBackPressed(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wellness_app.ChromeFlutterApi.onBackPressed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onInsetsChanged(insets insetsArg: ChromeInsets, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wellness_app.ChromeFlutterApi.onInsetsChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([insetsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
